In [7]:
import os
import sys
sys.path.append(os.path.join(os.getcwd(),'..','src'))
from utils import *


In [8]:
import torch
print(torch.__version__)

1.13.0


## Torch basics

In [9]:
vector = torch.tensor([7,7])
vector.shape, vector.ndim

(torch.Size([2]), 1)

In [10]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX.shape, MATRIX.ndim

(torch.Size([2, 2]), 2)

In [12]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR.shape, TENSOR.ndim

(torch.Size([1, 3, 3]), 3)

In [13]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [15]:
TENSOR[0][0]

tensor([1, 2, 3])

In [16]:
TENSOR[0][0][0]

tensor(1)

In [19]:
var = torch.tensor([[[1,2,3],
                     [4,5,6],
                     [7,8,9]],
                    [[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
var.shape, var.ndim

(torch.Size([2, 3, 3]), 3)

### Random Tensors
Random tensors are important because neural networks learn by starting with tensors full of random numbers that are slowly adjusted to better represent the data.

In [22]:
random_tensor = torch.rand(3, 3,4)
random_tensor, random_tensor.shape, random_tensor.ndim

(tensor([[[0.9008, 0.3126, 0.5461, 0.2034],
          [0.4481, 0.3491, 0.6650, 0.0180],
          [0.7232, 0.7312, 0.6140, 0.8364]],
 
         [[0.7594, 0.8230, 0.0320, 0.2803],
          [0.6889, 0.2488, 0.6385, 0.3372],
          [0.4214, 0.0788, 0.9248, 0.5670]],
 
         [[0.3019, 0.6215, 0.2993, 0.4001],
          [0.4399, 0.0860, 0.5321, 0.0252],
          [0.9851, 0.1950, 0.8599, 0.5815]]]),
 torch.Size([3, 3, 4]),
 3)

In [23]:
image_tensor = torch.rand(size=(224, 224, 3)) #Ht, Width, Color channels
image_tensor.shape, image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [24]:
zeros = torch.zeros(size=(3,4))
zeros.shape, zeros.ndim, zeros

(torch.Size([3, 4]),
 2,
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [25]:
ones = torch.ones(size=(3,4))
ones.shape, ones.ndim, ones

(torch.Size([3, 4]),
 2,
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

A range of tensors and tensors-like

In [28]:
torch.arange(0,12, 2)

tensor([ 0,  2,  4,  6,  8, 10])

In [29]:
one_to_ten = torch.zeros_like(input = torch.arange(1,11))
one_to_ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device = None,
                               requires_grad = False #Whether to track gradient for this tensor
                               )
float_32_tensor.dtype

torch.float32

Though dtype is specified as None, the default for PyTorch is float32.

The 3 main types of errors
1. Tensors not right data type -  use `tensor.dtype`
2. Tensors not the right shape - use `tensor.shape`
3. Tensors not on the right device -  use `tensor.device`

In [33]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

Get important tensor attributes

In [34]:
float_16_tensor.dtype, float_16_tensor.shape, float_16_tensor.device

(torch.float16, torch.Size([3]), device(type='cpu'))

## Tensor operations

In [39]:
tensor = torch.tensor([1,2,3])
tensor + 10, tensor * 10, tensor %10

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([1, 2, 3]))

Element-wise multiplication

In [40]:
tensor, tensor * tensor

(tensor([1, 2, 3]), tensor([1, 4, 9]))

Matirx-wise multiplication (dot-product)
* Note that the inner dimensions must match! i.e. a 3x2 matrix can be multiplied with a 2x3 matrix, not a 3x2 matrix.

In [41]:
torch.matmul(tensor, tensor)

tensor(14)